CREATE TABLE ITDE1.WEXZ_SALARY_HIST AS
(
SELECT  PERSON,
        CLASS,
        SALARY,
        DT AS EFFECTIVE_FROM,
        COALESCE(LEAD(DT) OVER(PARTITION BY PERSON ORDER BY DT) - INTERVAL '1' DAY,TO_DATE('2999/01/01', 'YYYY/MM/DD')) AS EFFECTIVE_TO
FROM DE.HISTGROUP
)

SELECT  P.PAYMENT_DT, 
        P.PERSON,
        P.PAYMENT,
        SUM(P.PAYMENT) OVER(PARTITION BY P.PERSON,TRUNC(P.PAYMENT_DT, 'MONTH') ORDER BY P.PAYMENT_DT) AS MONTH_PAID,
        SH.SALARY - SUM(P.PAYMENT) OVER(PARTITION BY P.PERSON,EXTRACT( MONTH FROM P.PAYMENT_DT) ORDER BY P.PAYMENT_DT) AS MONTH_REST
FROM DE.PAYMENTS P
LEFT JOIN ITDE1.WEXZ_SALARY_HIST SH
ON P.PAYMENT_DT BETWEEN SH.EFFECTIVE_FROM AND SH.EFFECTIVE_TO
AND P.PERSON = SH.PERSON