SELECT  PERSON,
        CLASS,
        EFFECTIVE_FROM,
        COALESCE(LEAD(EFFECTIVE_FROM) OVER(PARTITION BY PERSON ORDER BY EFFECTIVE_FROM) - INTERVAL '1' DAY,TO_DATE('2999/01/01', 'YYYY/MM/DD')) AS EFFECTIVE_TO
FROM    (SELECT  PERSON,
                CLASS,
                (CASE WHEN CLASS <> LAG(CLASS) OVER(PARTITION BY PERSON ORDER BY DT)
                    OR LAG(CLASS) OVER(PARTITION BY PERSON ORDER BY DT) IS NULL
                    THEN 1
                    ELSE 0 
                END) AS FLAG,
                DT AS EFFECTIVE_FROM
        FROM DE.HISTGROUP
        )
WHERE   FLAG = 1