-- 1. Clearing data from STG

delete from ITDE1.WEXZ_STG_ACCOUNTS;
delete from ITDE1.WEXZ_STG_CARDS;
delete from ITDE1.WEXZ_STG_CLIENTS;
delete from ITDE1.WEXZ_STG_PSSPRT_BLCKLST;
delete from ITDE1.WEXZ_STG_TERMINALS;
delete from ITDE1.WEXZ_STG_TRANSACTIONS;

delete from ITDE1.WEXZ_STG_DEL;

-- python code starts here
-- python take car of fiding increment of [passports, terminals]
-- ITDE1.WEXZ_META_LOAD updates here

-- 2. Capturing data from source to STG

-- capture data from database

INSERT INTO ITDE1.WEXZ_STG_ACCOUNTS( ACCOUNT,VALID_TO,CLIENT,CREATE_DT,UPDATE_DT)
SELECT 
	ACCOUNT,
	VALID_TO,
	CLIENT,
	CREATE_DT,
	UPDATE_DT
FROM BANK.ACCOUNTS
WHERE CREATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_ACCOUNTS_HIST'
)
OR UPDATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_ACCOUNTS_HIST'
);


INSERT INTO ITDE1.WEXZ_STG_CARDS(CARD_NUM,ACCOUNT,CREATE_DT,UPDATE_DT)
SELECT 
	CARD_NUM,
	ACCOUNT,
	CREATE_DT,
	UPDATE_DT
FROM BANK.CARDS
WHERE CREATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_CARDS_HIST'
)
OR UPDATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_CARDS_HIST'
);


INSERT INTO ITDE1.WEXZ_STG_CLIENTS( CLIENT_ID,LAST_NAME,FIRST_NAME,PATRONYMIC,DATE_OF_BIRTH,PASSPORT_NUM,PASSPORT_VALID_TO,PHONE,CREATE_DT,UPDATE_DT)
SELECT 
	CLIENT_ID,
	LAST_NAME,
	FIRST_NAME,
	PATRONYMIC,
	DATE_OF_BIRTH,
	PASSPORT_NUM,
	PASSPORT_VALID_TO,
	PHONE,
	CREATE_DT,
	UPDATE_DT
FROM BANK.CLIENTS
WHERE CREATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_CLIENTS_HIST'
)
OR UPDATE_DT > (
	SELECT LAST_UPDATE FROM ITDE1.WEXZ_META_DATE WHERE DBNAME = 'ITDE1' AND TABLENAME = 'WEXZ_DWH_DIM_CLIENTS_HIST'
);

-- 3 inserting data into the dwh

-- Inserting facts

INSERT INTO ITDE1.WEXZ_DWH_FACT_TRANSACTIONS(TRANS_ID,TRANS_DATE,CARD_NUM,OPER_TYPE,AMT,OPER_RESULT,TERMINAL)
SELECT
	TRANS_ID,
	to_date( TRANS_DATE, 'YYYY-MM-DD hh24:mi:ss' ),
	CARD_NUM,
	OPER_TYPE,
	REPLACE(AMT,',','.'),
	OPER_RESULT,
	TERMINAL
FROM  ITDE1.WEXZ_STG_TRANSACTIONS;


INSERT INTO ITDE1.WEXZ_DWH_FACT_PSSPRT_BLCKLST(PASSPORT_NUM,ENTRY_DT)
SELECT	PASSPORT_NUM,
		to_date( ENTRY_DT, 'YYYY-MM-DD' )	
FROM ITDE1.WEXZ_STG_PSSPRT_BLCKLST;


-- Inserting dimentions

insert into ITDE1.WEXZ_DWH_DIM_TERMINALS_HIST(TERMINAL_ID,TERMINAL_TYPE,TERMINAL_CITY,TERMINAL_ADDRESS,EFFECTIVE_FROM,EFFECTIVE_TO,DELETED_FLG)
select
	TERMINAL_ID,
	TERMINAL_TYPE,
	TERMINAL_CITY,
	TERMINAL_ADDRESS,
	to_date( DAY_OF_LOAD, 'DDMMYYYY' ),
	to_date( '2999-12-31', 'YYYY-MM-DD' ),
	'N'
from ITDE1.WEXZ_STG_TERMINALS;

merge into ITDE1.WEXZ_DWH_DIM_TERMINALS_HIST target1
using ITDE1.WEXZ_STG_TERMINALS stg1
on ( target1.TERMINAL_ID = stg1.TERMINAL_ID and target1.EFFECTIVE_FROM < to_date( stg1.DAY_OF_LOAD, 'DDMMYYYY' ))
when matched then update set 
    target1.EFFECTIVE_TO = to_date( stg1.DAY_OF_LOAD, 'DDMMYYYY' ) - interval '1' second
		where target1.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );		
		
insert into ITDE1.WEXZ_DWH_DIM_ACCOUNTS_HIST( ACCOUNT_NUM,VALID_TO,CLIENT,EFFECTIVE_FROM,EFFECTIVE_TO,DELETED_FLG)
select   
	ACCOUNT,
	VALID_TO,
	CLIENT,
	COALESCE(UPDATE_DT,CREATE_DT),
	to_date( '2999-12-31', 'YYYY-MM-DD' ),
	'N'
from ITDE1.WEXZ_STG_ACCOUNTS;

merge into ITDE1.WEXZ_DWH_DIM_ACCOUNTS_HIST target1
using ITDE1.WEXZ_STG_ACCOUNTS stg1
on ( target1.ACCOUNT_NUM = stg1.ACCOUNT and target1.EFFECTIVE_FROM < COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT))
when matched then update set 
    target1.EFFECTIVE_TO = COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT) - interval '1' second
		where target1.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );
		
			
insert into ITDE1.WEXZ_DWH_DIM_CARDS_HIST(CARD_NUM,ACCOUNT_NUM,EFFECTIVE_FROM,EFFECTIVE_TO,DELETED_FLG)
select   
	CARD_NUM,
	ACCOUNT,
	COALESCE(UPDATE_DT,CREATE_DT),
	to_date( '2999-12-31', 'YYYY-MM-DD' ),
	'N'
from ITDE1.WEXZ_STG_CARDS;

merge into ITDE1.WEXZ_DWH_DIM_CARDS_HIST target1
using ITDE1.WEXZ_STG_CARDS stg1
on ( target1.CARD_NUM = stg1.CARD_NUM and target1.EFFECTIVE_FROM < COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT))
when matched then update set 
    target1.EFFECTIVE_TO = COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT) - interval '1' second
		where target1.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );


insert into ITDE1.WEXZ_DWH_DIM_CLIENTS_HIST(CLIENT_ID,LAST_NAME,FIRST_NAME,PATRONYMIC,DATE_OF_BIRTH,
						PASSPORT_NUM,PASSPORT_VALID_TO,PHONE,EFFECTIVE_FROM,EFFECTIVE_TO,DELETED_FLG)
select   
	CLIENT_ID,
	LAST_NAME,
	FIRST_NAME,
	PATRONYMIC,
	DATE_OF_BIRTH,
	PASSPORT_NUM,
	PASSPORT_VALID_TO,
	PHONE,
	COALESCE(UPDATE_DT,CREATE_DT),
	to_date( '2999-12-31', 'YYYY-MM-DD' ),
	'N'
from ITDE1.WEXZ_STG_CLIENTS;

merge into ITDE1.WEXZ_DWH_DIM_CLIENTS_HIST target1
using ITDE1.WEXZ_STG_CLIENTS stg1
on ( target1.CLIENT_ID = stg1.CLIENT_ID and target1.EFFECTIVE_FROM < COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT))
when matched then update set 
    target1.EFFECTIVE_TO = COALESCE(stg1.UPDATE_DT,stg1.CREATE_DT) - interval '1' second
		where target1.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );


-- 4. take keys to check deletions

INSERT INTO ITDE1.WEXZ_STG_DEL(source_name,ID)
SELECT  'ACCOUNTS',
        ACCOUNT
FROM BANK.ACCOUNTS;


INSERT INTO ITDE1.WEXZ_STG_DEL(source_name,ID)
SELECT  'CARDS',
        CARD_NUM
FROM BANK.CARDS;


INSERT INTO ITDE1.WEXZ_STG_DEL(source_name,ID)
SELECT  'CLIENTS',
        CLIENT_ID
FROM BANK.CLIENTS;

-- 5. mark deleted records in the target tables

UPDATE ITDE1.WEXZ_DWH_DIM_TERMINALS_HIST tar
SET DELETED_FLG = 'Y',
EFFECTIVE_TO = sysdate
WHERE tar.TERMINAL_ID IN (
    SELECT	WEXZ_DWH_DIM_TERMINALS_HIST.TERMINAL_ID
    FROM ITDE1.WEXZ_DWH_DIM_TERMINALS_HIST
    LEFT JOIN ITDE1.WEXZ_STG_DEL
    ON WEXZ_DWH_DIM_TERMINALS_HIST.TERMINAL_ID = WEXZ_STG_DEL.id
	AND WEXZ_STG_DEL.source_name = 'terminals'
    WHERE WEXZ_STG_DEL.id IS NULL
	)
AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY/MM/DD');


UPDATE ITDE1.WEXZ_DWH_DIM_ACCOUNTS_HIST tar
SET DELETED_FLG = 'Y',
EFFECTIVE_TO = SYSDATE
WHERE tar.account_num IN (
    SELECT	WEXZ_DWH_DIM_ACCOUNTS_HIST.account_num
    FROM ITDE1.WEXZ_DWH_DIM_ACCOUNTS_HIST
    LEFT JOIN ITDE1.WEXZ_STG_DEL
    ON WEXZ_DWH_DIM_ACCOUNTS_HIST.account_num = WEXZ_STG_DEL.id
    AND WEXZ_STG_DEL.source_name = 'ACCOUNTS'
    WHERE WEXZ_STG_DEL.id IS NULL
	)
AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY/MM/DD');


UPDATE ITDE1.WEXZ_DWH_DIM_CARDS_HIST tar
SET DELETED_FLG = 'Y',
EFFECTIVE_TO = sysdate
WHERE tar.card_num IN (
    SELECT	WEXZ_DWH_DIM_CARDS_HIST.card_num
    FROM ITDE1.WEXZ_DWH_DIM_CARDS_HIST
    LEFT JOIN ITDE1.WEXZ_STG_DEL
    ON WEXZ_DWH_DIM_CARDS_HIST.card_num = WEXZ_STG_DEL.id
	AND WEXZ_STG_DEL.source_name = 'CARDS'
    WHERE WEXZ_STG_DEL.id IS NULL
	)
AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY/MM/DD');


UPDATE ITDE1.WEXZ_DWH_DIM_CLIENTS_HIST tar
SET DELETED_FLG = 'Y',
EFFECTIVE_TO = sysdate
WHERE tar.client_id IN (
    SELECT	WEXZ_DWH_DIM_CLIENTS_HIST.client_id
    FROM ITDE1.WEXZ_DWH_DIM_CLIENTS_HIST
    LEFT JOIN ITDE1.WEXZ_STG_DEL
    ON WEXZ_DWH_DIM_CLIENTS_HIST.client_id = WEXZ_STG_DEL.id
	AND WEXZ_STG_DEL.source_name = 'CLIENTS'
    WHERE WEXZ_STG_DEL.id IS NULL
	)
AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY/MM/DD');

--6 update the metadata

UPDATE ITDE1.WEXZ_META_DATE 
SET last_update = ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_ACCOUNTS )
WHERE 1=1
	AND dbname = 'ITDE1' 
	AND tablename = 'WEXZ_DWH_DIM_ACCOUNTS_HIST' 
	AND ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_ACCOUNTS ) IS NOT NULL;


UPDATE ITDE1.WEXZ_META_DATE 
SET last_update = ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_CARDS )
WHERE 1=1
	AND dbname = 'ITDE1' 
	AND tablename = 'WEXZ_DWH_DIM_CARDS_HIST' 
	AND ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_CARDS ) IS NOT NULL;
	

UPDATE ITDE1.WEXZ_META_DATE 
SET last_update = ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_CLIENTS )
WHERE 1=1
	AND dbname = 'ITDE1' 
	AND tablename = 'WEXZ_DWH_DIM_CLIENTS_HIST' 
	AND ( SELECT MAX( COALESCE(UPDATE_DT,CREATE_DT) ) FROM ITDE1.WEXZ_STG_CLIENTS ) IS NOT NULL;
	
	
UPDATE ITDE1.WEXZ_META_DATE 
SET last_update = ( SELECT MAX( TO_DATE(entry_dt,'YYYY-MM-DD') ) FROM ITDE1.WEXZ_STG_PSSPRT_BLCKLST )
WHERE 1=1
	AND dbname = 'ITDE1' 
	AND tablename = 'WEXZ_DWH_FACT_PSSPRT_BLCKLST' 
	AND ( SELECT MAX( TO_DATE(entry_dt,'YYYY-MM-DD') ) FROM ITDE1.WEXZ_STG_PSSPRT_BLCKLST ) IS NOT NULL;
